Repository DZhangCoder/Project-2, pull requests merged in 2019-06, with the labels that each got.

#22 Blakes branch
  config/config.json
  db/schema.sql
  db/seeds.sql
  models/example.js
  models/schema.sql
  models/student.js
  models/tasks.js
  models/teacher.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  routes/student-api-routes.js
  routes/task-api-routes.js
  routes/teacher-api-routes.js
  server.js
  test/canary.test.js
Labels: Models

#24 Kalebs branch
  public/index.html
Labels: View

#25 Kalebs branch
  public/index.html
  public/js/studentBrowse.js
  public/js/studentPost.js
  public/js/teacherBrowse.js
  public/js/teacherPost.js
  public/student_browse.html
Labels: View

#27 re added the index.js file and got the student post file into a minor…
  public/index.html
  public/js/index.js
  public/student_browse.html
  public/student_post.html
Labels: View

#31 merged master and re routed our error 404 page
  public/404.html
Labels: View

#32 Kalebs branch
  public/index.html
  public/student_homepage.html
  public/student_post.html
Labels: View

#40 commented to show where google stuff is at so we can modelize it later
  server.js
Labels: Routes

#42 re added the student browse section
  public/js/studentBrowse.js
Labels: View

#43 Blakes branch
  models/student.js
  test/recipes.test.js
Labels: enhancement

#44 google stuffs
  config/passport-setup.js
  routes/googleRoutes/auth-routes.js
  server.js
Labels: enhancement

#45 More google stuffs
  config/passport-setup.js
  models/student.js
  routes/googleRoutes/auth-routes.js
  routes/student-api-routes.js
Labels: enhancement

#53 Kalebs
  config/passport-setup.js
  public/index.html
  public/login.html
  routes/googleRoutes/auth-routes.js
  routes/htmlRoutes.js
Labels: enhancement

#55 google stuffs
  config/passport-setup.js
  package-lock.json
  package.json
  public/js/studentBrowse.js
  routes/googleRoutes/auth-routes.js
  routes/htmlRoutes.js
  server.js
Labels: enhancement

#58 some google route changes trying to log
  config/passport-setup.js
  public/html/404.html
  public/html/index.html
  public/html/login.html
  public/html/student_homepage.html
  public/html/student_post.html
  public/html/teacher_browse.html
  public/html/teacher_homepage.html
  public/html/teacher_post.html
  public/js/studentBrowse.js
  public/student_post.html
  routes/googleRoutes/auth-routes.js
  routes/htmlRoutes.js
Labels: enhancement

#61 View
  public/js/studentPost.js
  public/js/teacherBrowse.js
  public/student_homepage.html
  public/student_post.html
  public/teacher_browse.html
  public/teacher_homepage.html
  public/teacher_post.html
  public/teacher_profiles.html
Labels: View

#67 refactored the whole application
  config/passport-setup.js
  models/teacher.js
  public/404.html
  public/js/studentBrowse.js
  public/js/studentPost.js
  public/js/teacherBrowse.js
  public/js/teacherHome.js
  public/js/teacherPost.js
  public/student_post.html
  public/styles/index.css
  public/styles/styles.css
  public/styles/teacher_borwse.css
  routes/googleRoutes/auth-routes.js
  routes/htmlRoutes.js
  routes/student-api-routes.js
  routes/teacher-api-routes.js
  server.js
  views/index.handlebars
  views/layouts/main.handlebars
  views/layouts/partials/teacher_homepage.html
  views/layouts/partials/teacher_post.html
  views/layouts/partials/teacher_profiles.html
  views/student_homepage.handlebars
  views/student_post.handlebars
  views/teacher_browse.handlebars
Labels: enhancement

#68 fixed major merge
  views/student_post.handlebars
Labels: Clearing code

#72 added the email handler for the posts
  models/tasks.js
  public/js/studentBrowse.js
  public/js/studentPost.js
  views/student_post.handlebars
Labels: enhancement

#75 got moment to work and parsed the created at time
  public/js/studentBrowse.js
  views/student_homepage.handlebars
Labels: enhancement
